name: NanoBudget
description: A simple yet powerful budgeting app
full_description: 'To be added<br>
<br>With a lot of features:
<br>- See all your transactions in a glance
<br>- Check if your accounts tally
<br>- Split transaction between accounts easily'
android: https://www.nanobudget.io
iOS: https://www.nanobudget.io
web: https://www.nanobudget.io
screenshots:
  - 1.png
producthunt: https://www.nanobudget.io
companies:
